name: 'clubhouse github action'
description: "github action to control clubhouse story's workflow state"
inputs:
  github_token:
    description: "the github token"
    required: true
  pr_number:
    description: "the number of current PR"
    required: true
  shortcut_api_token:
    description: "shortcut api token"
    required: true
  pr_opened:
    description: "desired shortcut workflow state if pr opened"
    required: true
  pr_closed:
    description: "desired shortcut workflow state if pr closed or merged"
    required: true
  wip_id:
    description: "desired shortcut workflow state if pr is working in progress"
    required: false
  wip_keyword:
    description: "The keyword which indicates the pr is working in progress"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
