name: Test

on:
  pull_request:
    types: [opened, synchronize, edited, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 'CH-GH-TEST'
      uses: anencore94/clubhouse-github-action@main
      with:
        pr_number: ${{ github.event.number }}
        clubhouse_api_token: ${{ secrets.CLUBHOUSE_API_TOKEN }}
        pr_opened: 500001413
        pr_merged: 500001409
        pr_closed: 500001409